In [26]:
#Проба
#!pip install transformers
from transformers import BertTokenizer, BertModel
import torch

#Загрузка предобученной модели
model = BertModel.from_pretrained('bert-base-uncased',
                                   output_hidden_states = True)

#Прямая связь с моделью
#model1.eval()
sent_vec=[]
tokenizer = BertTokenizer.from_pretrained ('bert-base-uncased')

text = "Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for.Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for.Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for.Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for.Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for.Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for.Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for.Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for.Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for.Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for. Here is the sentence I want embeddings for."
marked_text = "[CLS]" + text + "[SEP]"

#Токенизируем предложение
tokenized_text = tokenizer.tokenize(marked_text)
print(len(tokenized_text))
if (len(tokenized_text) > 512):
  val_steck = []
  te = tokenized_text[1:-1]
  for i in range(int(len(te)/510)+1):
    if (i == int(len(te)/510)):
      ma = te[i*510:]
    else:
      ma = te[i*510:i*510+510]
    ma.insert(0,'[CLS]')
    ma.append('[SEP]')  
    indexed_tokens = tokenizer.convert_tokens_to_ids(ma)
    segments_ids = [1] * len(ma)
    tokens_tensor = torch.tensor([indexed_tokens])
    segments_tensors = torch.tensor([segments_ids])
    with torch.no_grad():
      outputs = model(tokens_tensor, segments_tensors)
    BERT_hidden_states = outputs[2]
    token_vecs = BERT_hidden_states[-2][0]
    if i !=0:
      p = torch.cat((val_steck[0], token_vecs), dim = 0)
      val_steck.clear()
      val_steck.append(p)
    if i == 0:
      val_steck.append(token_vecs)

  #Среднее значение токенов
  sentence_embedding = torch.mean(val_steck[0], dim = 0)

  print("Our final sentence embedding vector of shape: ", sentence_embedding.size())
  sent_vec.append(sentence_embedding.numpy())
print(sent_vec)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


1562
Our final sentence embedding vector of shape:  torch.Size([768])
[array([-5.02425194e-01, -2.87718717e-02,  2.74853408e-01, -3.31751257e-01,
        2.81962931e-01,  2.23265663e-01,  5.56561314e-02,  1.24436356e-01,
        4.25312761e-03, -7.04053044e-02,  3.44573706e-02, -3.41367960e-01,
       -6.15066946e-01,  3.64447653e-01,  1.16205893e-01,  5.15552044e-01,
        5.72726689e-02,  6.14550486e-02,  1.76378433e-02,  1.02392711e-01,
        8.69170070e-01,  1.59030199e-01, -3.88357759e-01,  2.92202324e-01,
        5.68527207e-02,  7.65767042e-03,  3.07705216e-02, -4.24151182e-01,
       -8.77343789e-02,  2.41560131e-01,  3.55441391e-01,  5.23754537e-01,
        1.11243874e-02, -7.36215711e-01, -1.37382612e-01, -2.51755983e-01,
        3.62532586e-01, -4.21589434e-01,  3.65791619e-01,  4.06339109e-01,
       -9.25773382e-01, -4.68734592e-01,  2.39879027e-01, -5.97166121e-01,
       -1.51263356e-01, -5.41348457e-01,  2.78511226e-01, -6.86573803e-01,
       -3.76295112e-02, -4.62

In [4]:
#Сопоставление словарных индексов для токенизированной строки
indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)

#Print results
for tup in zip(tokenized_text, indexed_tokens):
  print('{:<12}{:>6,}'.format(tup[0], tup[1]))

[CLS]          101
here         2,182
is           2,003
the          1,996
sentence     6,251
i            1,045
want         2,215
em           7,861
##bed        8,270
##ding       4,667
##s          2,015
for          2,005
.            1,012
here         2,182
is           2,003
the          1,996
sentence     6,251
i            1,045
want         2,215
em           7,861
##bed        8,270
##ding       4,667
##s          2,015
for          2,005
.            1,012
here         2,182
is           2,003
the          1,996
sentence     6,251
i            1,045
want         2,215
em           7,861
##bed        8,270
##ding       4,667
##s          2,015
for          2,005
.            1,012
here         2,182
is           2,003
the          1,996
sentence     6,251
i            1,045
want         2,215
em           7,861
##bed        8,270
##ding       4,667
##s          2,015
for          2,005
.            1,012
here         2,182
is           2,003
the          1,996
sentence    

In [4]:
#помеаем каждый токен цифрой предложения, к которому он принадлежит
segments_ids = [1] * len(tokenized_text)
print(segments_ids)

tokens_tensor = torch.tensor([indexed_tokens])
segments_tensors = torch.tensor([segments_ids])

print(segments_tensors)
print(tokens_tensor)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[ 101, 2182, 2003, 1996, 6251, 1045, 2215, 7861, 8270, 4667, 2015, 2005,
         1012,  102]])


In [5]:
#Запускаем текст через берта и собираем все скрытые состояния 12 слоев

with torch.no_grad():
  outputs = model(tokens_tensor, segments_tensors)

In [6]:
outputs.keys()
#ПроверяемБ что 3 компонента - скрытый параметр из каждого слоя

odict_keys(['last_hidden_state', 'pooler_output', 'hidden_states'])

In [7]:
BERT_hidden_states = outputs[2]
BERT_hidden_states

(tensor([[[ 0.1686, -0.2858, -0.3261,  ..., -0.0276,  0.0383,  0.1640],
          [-0.3557,  0.9575, -1.3448,  ...,  0.5972,  0.7392,  0.2581],
          [-0.6270, -0.0633, -0.3143,  ...,  0.3427,  0.4636,  0.4594],
          ...,
          [-0.1977,  0.5124, -0.7430,  ...,  0.4438,  0.7002,  0.6790],
          [-0.4543,  0.4021,  0.0275,  ...,  0.4682,  0.4795,  0.7025],
          [-0.6056,  0.0968,  0.1880,  ..., -0.2773,  0.1849,  0.0580]]]),
 tensor([[[ 0.0212,  0.0978, -0.2176,  ...,  0.2098, -0.0370,  0.0035],
          [-0.6961,  1.1623, -1.4048,  ...,  0.3229,  0.8464,  0.4431],
          [-0.9514, -0.4736, -0.4308,  ...,  0.2475,  0.6113,  0.4343],
          ...,
          [ 0.4304,  0.4929, -0.6780,  ...,  0.1534,  0.7755,  0.3170],
          [-0.4537,  0.2565,  0.0719,  ...,  0.3848,  0.0583,  0.4297],
          [-0.4741,  0.0288,  0.0707,  ..., -0.1558,  0.1840,  0.1237]]]),
 tensor([[[-0.1364, -0.2169, -0.3929,  ...,  0.4501,  0.0688, -0.0071],
          [-0.7417,  1.7412,

In [8]:
BERT_hidden_states_also = outputs.hidden_states

Преобразование в вектор

In [9]:
#1
token_embeddings = torch.stack(BERT_hidden_states, dim = 0)
token_embeddings.size()

torch.Size([13, 1, 14, 768])

In [10]:

token_embeddings = torch.squeeze(token_embeddings, dim = 1)
token_embeddings.size()

torch.Size([13, 14, 768])

In [11]:
#14 tokens, 13 layers
token_embeddings = token_embeddings.permute(1,0,2)
token_embeddings.size()

torch.Size([14, 13, 768])

1 способ. Конкатинация последних 4 слоев

In [12]:
token_vecs_cat = [] #shape [14*3,072]

#token_embeddings is [14*13*768] tensor
#Для каждого токена в предложении:

for token in token_embeddings:
  #token is [13*768]
  #cat_vec is length = 4*768
  cat_vec = torch.cat((token[-1], token[-2],token[-3],token[-4]), dim = 0)

  #Используем cat_vec чтобы представить токен
  token_vecs_cat.append(cat_vec)

print('Shape is: %d * %d' % (len(token_vecs_cat), len(token_vecs_cat[0])))
#Теперь для каждого токена (слова) у нас есть вектор 3072 размерности


Shape is: 14 * 3072


2 способ. Сложение 4 последних слоев

In [13]:
token_vecs_sum = [] # [14*768]

for token in token_embeddings:
  sum_vec = torch.sum(token[-4:], dim = 0)
  token_vecs_sum.append(sum_vec)

print('Shape is: %d * %d' % (len(token_vecs_sum), len(token_vecs_sum[0])))
#Теперь для каждого токена (слова) у нас есть вектор 768 размерности

Shape is: 14 * 768


Вектор для предложений
Самый простой спопоб - среднее от 2 до последнего слоя. Получаем вектор длины 768

In [14]:
# hidden_states is [13*1*14*768]
# token_vecs is [14*768]

#second to last hidden layers
token_vecs = BERT_hidden_states[-2][0]
print('token_vecs.shape = ', token_vecs.shape)

#Среднее значение 14 токенов
sentence_embedding = torch.mean(token_vecs, dim = 0)

print("Our final sentence embedding vector of shape: ", sentence_embedding.size())

token_vecs.shape =  torch.Size([14, 768])
Our final sentence embedding vector of shape:  torch.Size([768])


In [17]:
sentence_embedding.detach().numpy()


array([-9.94422566e-03, -2.73203671e-01, -1.04156090e-02, -4.84079830e-02,
       -2.47512460e-01,  1.19131967e-01,  1.95329394e-02,  2.82477140e-01,
        1.16199717e-01, -2.17530593e-01,  2.44662359e-01, -2.35441238e-01,
       -1.69134125e-01,  3.76003504e-01, -1.27432272e-01,  5.64782143e-01,
       -4.54765022e-01, -1.20368190e-01,  8.38750154e-02, -2.85714895e-01,
        3.49823415e-01,  5.23198307e-01, -2.60375112e-01,  7.41746947e-02,
        3.81481916e-01, -1.87159970e-01, -2.89616525e-01, -1.84148103e-01,
       -4.09228623e-01,  1.33154735e-01,  5.69894314e-02,  4.45717633e-01,
       -1.24349371e-01, -7.33190715e-01, -5.26218787e-02, -1.91462919e-01,
        1.05111614e-01, -4.91017640e-01,  3.62757756e-03,  1.80926651e-01,
       -5.83285511e-01, -2.62456685e-01,  3.30721855e-01, -3.49757463e-01,
       -2.00462248e-02,  5.68123460e-02, -3.79718333e-01, -4.27065432e-01,
       -9.77941826e-02, -2.82309264e-01, -1.00384033e+00,  3.35105181e-01,
        1.42834276e-01,  

CLS token - last hidden state

In [ ]:
lhs_tensor = outputs.last_hidden_state
print(lhs_tensor.size())
lhs_tensor

torch.Size([1, 14, 768])


tensor([[[-0.0388, -0.0496,  0.0681,  ..., -0.0965,  0.1445,  0.8142],
         [-0.5943, -1.0473,  0.2573,  ..., -0.2575, -0.1272, -0.1501],
         [ 0.0465, -0.7444,  0.2833,  ...,  0.2284,  0.0208,  0.3949],
         ...,
         [ 0.5742,  0.2906,  0.3866,  ...,  0.3603, -0.2322,  0.0978],
         [ 0.9234,  0.2302, -0.3533,  ...,  0.2503, -0.5980, -0.4933],
         [ 1.0368,  0.3106, -0.2125,  ...,  0.3229, -0.7453, -0.3948]]])

In [ ]:
cls_tensor = lhs_tensor[:,0,:]
cls_tensor
#the hidden representation of CLS token as a repr. of the whole sequence

tensor([[-3.8821e-02, -4.9612e-02,  6.8122e-02, -2.9851e-01, -2.9840e-01,
         -3.0842e-01,  3.0120e-02,  2.0229e-01,  1.8005e-01, -1.4553e-01,
          2.0532e-01,  1.4376e-02, -6.0990e-02,  6.6026e-02,  3.2963e-01,
          3.7979e-03, -2.1175e-01,  3.7744e-01,  1.4625e-01, -2.0243e-01,
          1.7214e-01, -5.8758e-02,  3.3683e-02, -2.2808e-01,  1.8304e-01,
         -3.0446e-02, -4.9751e-02, -1.2970e-01, -1.9525e-01,  9.2727e-02,
          6.3092e-02,  1.2827e-01, -1.8259e-01, -1.0227e-01,  2.3424e-01,
          1.1938e-01,  3.1091e-01, -2.5228e-01,  2.8242e-01, -2.4837e-01,
         -2.3287e-01, -8.0056e-04,  2.2632e-01, -1.1506e-01,  1.1957e-01,
         -3.0994e-01, -2.9033e+00, -1.6620e-01, -3.3403e-01, -1.8791e-01,
         -1.3200e-02, -3.5992e-02,  2.9946e-01,  2.8467e-01,  9.2990e-02,
          9.8315e-02, -2.5048e-01,  3.2162e-01,  1.9736e-01, -1.2443e-01,
          1.7249e-01,  2.9085e-01,  2.3598e-03,  8.8091e-03, -2.6255e-01,
          3.1879e-01, -1.2396e-01,  1.

In [ ]:
cls_tensor

tensor([[-3.8821e-02, -4.9612e-02,  6.8122e-02, -2.9851e-01, -2.9840e-01,
         -3.0842e-01,  3.0120e-02,  2.0229e-01,  1.8005e-01, -1.4553e-01,
          2.0532e-01,  1.4376e-02, -6.0990e-02,  6.6026e-02,  3.2963e-01,
          3.7979e-03, -2.1175e-01,  3.7744e-01,  1.4625e-01, -2.0243e-01,
          1.7214e-01, -5.8758e-02,  3.3683e-02, -2.2808e-01,  1.8304e-01,
         -3.0446e-02, -4.9751e-02, -1.2970e-01, -1.9525e-01,  9.2727e-02,
          6.3092e-02,  1.2827e-01, -1.8259e-01, -1.0227e-01,  2.3424e-01,
          1.1938e-01,  3.1091e-01, -2.5228e-01,  2.8242e-01, -2.4837e-01,
         -2.3287e-01, -8.0056e-04,  2.2632e-01, -1.1506e-01,  1.1957e-01,
         -3.0994e-01, -2.9033e+00, -1.6620e-01, -3.3403e-01, -1.8791e-01,
         -1.3200e-02, -3.5992e-02,  2.9946e-01,  2.8467e-01,  9.2990e-02,
          9.8315e-02, -2.5048e-01,  3.2162e-01,  1.9736e-01, -1.2443e-01,
          1.7249e-01,  2.9085e-01,  2.3598e-03,  8.8091e-03, -2.6255e-01,
          3.1879e-01, -1.2396e-01,  1.

In [ ]:
cls_tensor.detach().numpy()

array([[-3.88214067e-02, -4.96124029e-02,  6.81222528e-02,
        -2.98509359e-01, -2.98403770e-01, -3.08424860e-01,
         3.01200617e-02,  2.02285960e-01,  1.80048019e-01,
        -1.45531148e-01,  2.05315664e-01,  1.43763190e-02,
        -6.09898493e-02,  6.60258085e-02,  3.29629093e-01,
         3.79789667e-03, -2.11749271e-01,  3.77444595e-01,
         1.46246389e-01, -2.02425212e-01,  1.72144651e-01,
        -5.87579980e-02,  3.36833969e-02, -2.28079930e-01,
         1.83042213e-01, -3.04463133e-02, -4.97507453e-02,
        -1.29699618e-01, -1.95249707e-01,  9.27270427e-02,
         6.30917996e-02,  1.28268868e-01, -1.82588264e-01,
        -1.02268577e-01,  2.34237999e-01,  1.19379587e-01,
         3.10909897e-01, -2.52276212e-01,  2.82423526e-01,
        -2.48372614e-01, -2.32874379e-01, -8.00560054e-04,
         2.26316646e-01, -1.15062900e-01,  1.19571067e-01,
        -3.09938967e-01, -2.90330005e+00, -1.66202024e-01,
        -3.34026486e-01, -1.87907979e-01, -1.32004246e-0